name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      # Étape 1: Vérifier le code du repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Se connecter à GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3: Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kavvet2/ue19-lab-05:${{ github.sha }} .

      # Étape 4: Publier l'image Docker sur GitHub Packages (GHCR)
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/kavvet2/ue19-lab-05:${{ github.sha }}
